version: '3'
services:
    redis-master:
        image: redis:latest
        network_mode: "host"
        command: redis-server --port 6379 
    redis-slave-1:
        image: redis:latest
        network_mode: "host"
        command: redis-server --port 6380 --slaveof ${HOST_IP} 6379
    redis-slave-2:
        image: redis:latest
        network_mode: "host" 
        command: redis-server --port 6381 --slaveof ${HOST_IP} 6379

    redis-sentinel-1:
        image: 'bitnami/redis-sentinel:latest'
        network_mode: "host" 
        environment:
            - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=15000
            - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
            - REDIS_MASTER_HOST=${HOST_IP}
            - REDIS_SENTINEL_PORT_NUMBER=26379
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
    redis-sentinel-2:
        image: 'bitnami/redis-sentinel:latest'
        network_mode: "host" 
        environment:
            - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=15000
            - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
            - REDIS_MASTER_HOST=${HOST_IP}
            - REDIS_SENTINEL_PORT_NUMBER=26380
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
    redis-sentinel-3:
        image: 'bitnami/redis-sentinel:latest'
        network_mode: "host" 
        environment:
            - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=15000
            - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
            - REDIS_MASTER_HOST=${HOST_IP}
            - REDIS_SENTINEL_PORT_NUMBER=26381
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
